services:
  web:
    build:
      context: .
      args:
        - HTTP_PROXY
        - HTTPS_PROXY
        - http_proxy
        - https_proxy
    command: python app.py
    # Ports removed to prevent direct access, only accessible via nginx
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///tabelog.db
      - FLASK_DEBUG=1
      - PROXY=${PROXY}
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "5000:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - web
    restart: always

  worker:
    build:
      context: .
      args:
        - HTTP_PROXY
        - HTTPS_PROXY
        - http_proxy
        - https_proxy
    command: python worker.py
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///tabelog.db
      - CHECK_INTERVAL=300
      - PROXY=${PROXY}
    restart: always
